version: "3.3"

services:
  php:
    build: docker/php
    ports:
      - 80:80
    volumes:
      - .:/opt/php
    working_dir: /opt/php
    networks:
      - admovil
    environment:
      XDEBUG_CONFIG: 
        remote_host=${REMOTE_HOST}
        remote_enable=1
      PHP_IDE_CONFIG: serverName=admovil

networks:
  admovil: ~
