version: "3.3"

services:
  php:
    build: $PWD/.docker/php
    ports:
      - 80:80
    volumes:
      - php:/opt/php
    working_dir: /opt/php
    environment:
      XDEBUG_CONFIG: 
        remote_host=${REMOTE_HOST}
        remote_enable=1
      PHP_IDE_CONFIG: serverName=admovil
    networks:
      - admovil

networks:
  admovil: ~

volumes:
  php:
    driver_opts:
      type: none
      device: $PWD
      o: bind
